collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5591819405090064
color:
  saturation: 0.5296652263496071
  brandStrength: 0.2734347388613969
  rhythmicContrast: 0.8283096386585385
  brandColors:
    - '#F9E4AD'
    - '#E6B098'
    - '#CC4452'
    - '#723147'
    - '#31152B'
  lightness: 0.010460634250193834
layout_spectrum: 0.5452385866083205
name: Clark's Essentials
title: natural delights | lovely things | tasty stuff | homemade
