name: Clark's Essentials
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a85a4396-058a-4563-9251-ddfc538024ad.jpg
layout_spectrum: 0.8978494
typography_spectrum: 0.92118
title: Clark's Essentials
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: natural delights | lovely things | tasty stuff | homemade
author:
  name: Amanda Clark
  email: mands007@mac.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecedf2'
    - '#2b2120'
    - '#a76765'
    - '#c5a8aa'
    - '#090305'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.327957
  rhythmicContrast: 0.5842294
purpose: []
