title: Clark's Essentials
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: natural delights | lovely things | tasty stuff | homemade
color:
  saturation: 0.327957
  brandStrength: 0.5878136
  lightness: 1
  brandColors:
    - '#B9C3C5'
    - '#898E94'
    - '#696A64'
    - '#4B5253'
    - '#353B3B'
  rhythmicContrast: 0.5842294
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
author:
  name: Amanda Clark
  email: mands007@mac.com
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a85a4396-058a-4563-9251-ddfc538024ad.jpg
opengraph:
  image: null
  type: null
  appId: null
name: Clark's Essentials
typography_spectrum: 0.9390681
layout_spectrum: 0.8978494
