name: Clark's Essentials
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a85a4396-058a-4563-9251-ddfc538024ad.jpg
layout_spectrum: 0.89499
typography_spectrum: 0.10507
author:
  name: Amanda Clark
  email: mands007@mac.com
navigation: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: >-
  Clark's Essentials... natural delights | lovely things | tasty stuff |
  homemade
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebd0b3'
    - '#77abd0'
    - '#c58953'
    - '#2c587f'
    - '#ee2396'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
