layout_spectrum: 0.813455379800871
typography_spectrum: 0.48785116081126034
color:
  saturation: 0.47583869425579906
  brandStrength: 0.8060220377519727
  rhythmicContrast: 0.40831335028633475
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  lightness: 0.697908082511276
title: Clark's Essentials
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: natural delights | lovely things | tasty stuff | homemade
cta:
  bucket: null
  version: null
  domain: null
name: Clark's Essentials
author:
  name: Amanda Clark
  email: mands007@mac.com
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a85a4396-058a-4563-9251-ddfc538024ad.jpg
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
