typography_spectrum: 0.3842382070142776
color:
  brandColors:
    - '#282142'
    - '#dac7c1'
    - '#983963'
    - '#dc9698'
    - '#996567'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.40958797046914697
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Amanda Clark
  email: mands007@mac.com
name: Clark's Essentials
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: fcbfdaeb-b918-4812-bebd-8e72f24fd7f1
    url: 2016-07-21-relaxing-diy-bath-salts.html
    name: Relaxing DIY Bath Salts
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a85a4396-058a-4563-9251-ddfc538024ad.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
purpose: []
