typography_spectrum: 0.42579508759081364
color:
  saturation: 0.5
  brandStrength: 0.5
  rhythmicContrast: 0.75
  brandColors:
    - '#ebd0b3'
    - '#77abd0'
    - '#c58953'
    - '#2c587f'
    - '#ee2396'
  lightness: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6263238859828562
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Amanda Clark
  email: mands007@mac.com
name: Clark's Essentials
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - id: b999fc9d-bea3-4b16-9714-ed3311f9bc95
    url: >-
      2016-07-23-natural-delights-or-lovely-things-or-tasty-stuff-or-homemade.html
    name: About
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a85a4396-058a-4563-9251-ddfc538024ad.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Clark's Essentials
purpose: []
